Operation:
    #Name
    Prefix: 'AT_WRN32_10_GNN_1'
    #Train
    Train: False
    #Resume
    Resume: True
    #Validate
    Validate: True
TRAIN:
    # Number of training epochs
    epochs: 200

    # Starting epoch
    start_epoch: 0

    # SGD paramters
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0002

    # Print frequency, is used for both training and testing
    print_freq: 10

    # Dataset mean and std used for data normalization
    mean: !!python/tuple [0.4914, 0.4822, 0.4465]
    std: !!python/tuple [0.2023, 0.1994, 0.2010]
    
ADV:
    # FGSM parameters during training
    clip_eps: 4
    fgsm_step: 8

    # Number of repeats for free adversarial training
    n_repeats: 8

    # PGD attack parameters used during validation
    # the same clip_eps as above is used for PGD
    pgd_attack: 
    - !!python/tuple [20, 2.0] #[10 iters, 8.0/255.0], 改动：zkj
    - !!python/tuple [100, 2.0] #[50 iters, 8.0/255.0]
    
DATA:
    # Number of data workers
    workers: 4

    # Training batch size
    batch_size: 128

    # Image Size
    img_size: 32

    # Crop Size for data augmentation
    crop_size: 32

    # Color value range
    max_color_value: 255.0

    
